### ISSUE TITLE
Document why the lib folder isn't checked in, and how to set up build environment.

### ISSUE THREAD

**Issue by ulrikaugustsson** [aickin/react-dom-stream#1]
Should the lib folder really be ignored? I guess that is where the magic happens and you can't get contributors if it's not committed.

**Comment by aickin** [comment]
Hey @ulrikaugustsson, thanks for opening this!

The lib folder's source is checked in; it comes from my fork of react [here](https://github.com/aickin/react/tree/streaming-render-0.14), and the majority of the interesting changes were in [this commit](https://github.com/aickin/react/commit/d650a52e806f110ebec971e048b1dbded53cacd6). I'm absolutely happy to accept contributions to the core logic in that repo!

I should write up a quick doc of how to set up the two projects if you want to contribute; if I have time this week, I'll do so. 

Thanks for the feedback!

**Comment by ulrikaugustsson** [comment]
Ah, cool. Will be interesting to see if this can get slimmer when they really break react-dom away from react.

Great work in any case. Unless you want this issue as a reminder to add docs you can close this.

**Comment by aickin** [comment]
Thanks! I'll keep it around as a documentation reminder

**Comment by aickin** [comment]
I added [CONTRIBUTING.md](https://github.com/aickin/react-dom-stream/blob/master/CONTRIBUTING.md) in 6647273e0d2, and hopefully it explains clearly how to get a build working, why `lib` isn't checked in, and how to contribute.

Closing now; thanks for the bug report!
