### ISSUE TITLE
Two copies of React

### ISSUE THREAD

**Issue by Sinewyk** [aickin/react-dom-stream#10]
Any way we could "cleanly" overload the exports of `'react-dom/server'` server side ?

I just checked a possible case where I would be using react-dom/server and react-dom-stream/server side by side and of course they are not using the same source files ...

Shouldn't react-dom-stream be used on with React as a peerDependency and actually instead of requiring something you copied into `./lib/`, for example
`var ReactDefaultBatchingStrategy = require('./ReactDefaultBatchingStrategy');`
you would actually require the real stuff, that is
`var ReactDefaultBatchingStrategy = require('react/lib/ReactDefaultBatchingStrategy');`

**Comment by aickin** [comment]
@Sinewyk Thanks for the issue report!

The changes to React are pretty invasive (and getting more so the more I work on 0.2.x), so I don't think I can use the internals from `react`. It's especially perilous given that these are all internal APIs we are talking about, so it means that `react-dom-stream` would be depending on shaky ground.

To be clear, are you getting the two copies of React warning on the server side? I have projects that use both react-dom/server and react-dom-stream/server, and I don't see this warning. Can you tell me more about what your test case looks like? Thanks!

**Comment by Sinewyk** [comment]
No, I don't have a problem per say. I just checked

```js
require('react');
require('react-dom/server');
require('react-dom-stream/server');

// what was loaded ?
Object.keys(require('module')._cache);
```


to exactly see what was loaded, and we get almost 100% duplication between
`./node_modules/react-dom-stream/lib/*`
and
`./node_modules/react-dom/lib/*`

I just supposed in the long run it's going to pose problems. Not because of two React copies (it's not like we are diffing server-side), just general code flow comprehension/bug tracking.

And maybe simply for you to be able to "properly" share the codebase here instead of doing some weird build step ^^.

I quickly took a look at ReactServerAsyncRendering IIRC, and I don't know how much you edited to make it work. But looking for a _better_ way should be worthwhile.

**Comment by RickWong** [comment]
You might be running into this bug: https://github.com/facebook/react/issues/5383
