### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by arjunskumar47** [aickin/react-dom-stream#24]
So I'm trying to stream my response and I'm getting special characters on the screen.

For instance, in my component I have `&nbsp;` which is translated to `Â` when streaming the response. If I use the native React renderToString it works fine

**Comment by arjunskumar47** [comment]
@aickin - Any thoughts on this?

**Comment by mhaagens** [comment]
I'm also having the same problem.

**Comment by arjunskumar47** [comment]
@mhaagens Were you able to figure out anything in regard to this?

**Comment by arjunskumar47** [comment]
Adding `<meta charset="utf-8" />` to the HTML head solved this for me.
