### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by OliverJAsh** [aickin/react-dom-stream#26]
Hi, thanks for the great project!

I am trying to find the code that powers `renderToString` to understand how you are making the virtual node into a stream, but it seems like the bulk of the code is omitted from the repository (`lib` and `dist` folders, referenced in https://github.com/aickin/react-dom-stream/blob/2a51da059b15bb7d53f022d19212ab82b07a3a17/server.js#L6). Do you know where I could find it?

Cheers,
Olly

**Comment by Peleg** [comment]
whops, just found this: https://github.com/aickin/react-dom-stream#wait-wheres-the-code

**Comment by OliverJAsh** [comment]
Thanks!
