### ISSUE TITLE
Dynamic meta tags / titles

### ISSUE THREAD

**Issue by geekyme** [aickin/react-dom-stream#6]
Not sure if this is the best place to report this issue.

I am actually using [react-helmet](https://github.com/nfl/react-helmet) to support a declarative way of writing head and title tags. It is really useful in the traditional way to rendering on the server side.

The trouble is that the information for these head / title tags are only available after a tree of components have finished `renderToString`-ed.

Since we are streaming components down, the head / title tags will always be undefined. Wondering if there's a way to avoid this issue or use a completely different design to write the head / meta tags.

**Comment by th0r** [comment]
@geekyme I think you'll have to choose another design to deal with document metadata.
I personally use `fluxible` store for this so I have all the metadata before actually rendering of the component's tree.

**Comment by aickin** [comment]
Yeah, I think that's a basic problem with the code flow in react-helmet; in a streaming world you can't let code after the `head` determine what's in the `head`. The react-helmet design is, at least as I read it, fundamentally hostile to streaming responses.

Thanks for the bug report, and keep them coming, they are helping me understand the scope of the problem. I'm going to close this one, though, as there's nothing I can do to change react-helmet's design.

**Comment by geekyme** [comment]
sure thanks @aickin

**Comment by bgannonPL** [comment]
Sorry to post on a closed topic but can't find a good solution to this problem (populating head tag when streaming) elsewhere. @th0r -- curious how you're approaching this (or anyone else).

**Comment by th0r** [comment]
@bgannonPL Here is my approach: https://github.com/aickin/react-dom-stream/issues/2#issuecomment-150165175
